#import "CADFontSupport.h"

#import <stdlib.h>

static NSString *kCADFontsCacheSubdirectory  = @"CADFonts";
static NSString *kCADFontsBundleSubdirectory = @"Fonts";
static NSString *kCADFontMapFileName         = @"FONTMAP.txt";

// Bundled font filenames — must match what is inside CADFP/Fonts/.
static NSString *const kCADShxPrimary  = @"hztxt.shx";   // primary CJK SHX bigfont
static NSString *const kCADShxSecondary= @"gbcbig.shx";  // secondary CJK SHX bigfont
static NSString *const kCADTtcFallback = @"NotoSansCJK-wght-400-900.ttf.ttc";

// ─────────────────────────────────────────────────────────────────────────────
// CRITICAL RULE FOR ODA FONTMAP:
//   • SHX bigfont names  →  must resolve to another .shx file.
//     Mapping an SHX name to a .ttf/.ttc is INVALID — ODA will try to use the
//     TTF as an SHX bigfont, fail, and Chinese will still show as "?".
//   • TTF family names   →  may resolve to a .ttf/.ttc (handled by FreeType).
//
// Therefore:
//   - hztxt and gbcbig are NOT listed here; findFile() will find them directly
//     via the ACAD search path.
//   - Unknown SHX names map to hztxt.shx (SHX → SHX substitution is valid).
//   - Windows CJK TTF family names map to the Noto TTC (TTF → TTF is valid).
// ─────────────────────────────────────────────────────────────────────────────
static NSString *CADDefaultFontMap(void)
{
    NSString *shxP = kCADShxPrimary;
    NSString *shxS = kCADShxSecondary;
    NSString *ttc  = kCADTtcFallback;

    NSMutableString *buf = [NSMutableString string];
    [buf appendString:@"# CADFP FONTMAP — auto-generated by CADFontSupport\n"];
    [buf appendString:@"# SHX->SHX and TTF->TTF only. Never map SHX to TTF.\n#\n"];

    // SHX bigfont names we do NOT have bundled → redirect to hztxt.shx
    NSArray<NSArray<NSString *> *> *shxRows = @[
        @[@"chinese",      shxP],
        @[@"chinese.shx",  shxP],
        @[@"hzst",         shxP],
        @[@"hzfs",         shxP],
        @[@"hzdx",         shxP],
        @[@"hzdx.shx",     shxP],
        @[@"hzxt",         shxP],
        @[@"hz",           shxP],
        @[@"tssdeng",      shxP],
        @[@"tssdeng.shx",  shxP],
        @[@"tssdchn",      shxP],
        @[@"tssdchn.shx",  shxP],
        @[@"gbenor",       shxS],   // regular SHX often paired with gbcbig
        @[@"gbenor.shx",   shxS],
        @[@"gbeitc",       shxS],
        @[@"gbeitc.shx",   shxS],
    ];

    // Windows CJK TTF family names → Noto Sans CJK TTC (TTF pipeline)
    NSArray<NSArray<NSString *> *> *ttfRows = @[
        @[@"宋体",            ttc],
        @[@"SimSun",          ttc],
        @[@"新宋体",          ttc],
        @[@"NSimSun",         ttc],
        @[@"仿宋",            ttc],
        @[@"仿宋_GB2312",     ttc],
        @[@"FangSong",        ttc],
        @[@"FangSong_GB2312", ttc],
        @[@"黑体",            ttc],
        @[@"SimHei",          ttc],
        @[@"楷体",            ttc],
        @[@"楷体_GB2312",     ttc],
        @[@"KaiTi",           ttc],
        @[@"KaiTi_GB2312",    ttc],
        @[@"微软雅黑",        ttc],
        @[@"Microsoft YaHei", ttc],
        @[@"华文细黑",        ttc],
        @[@"STHeiti",         ttc],
        @[@"华文黑体",        ttc],
        @[@"等线",            ttc],
        @[@"DengXian",        ttc],
    ];

    [buf appendString:@"# SHX bigfont substitutions (SHX → SHX):\n"];
    for (NSArray<NSString *> *row in shxRows) {
        [buf appendFormat:@"%@;%@\n", row[0], row[1]];
    }
    [buf appendString:@"# TTF family substitutions (TTF → TTF):\n"];
    for (NSArray<NSString *> *row in ttfRows) {
        [buf appendFormat:@"%@;%@\n", row[0], row[1]];
    }
    return buf;
}

// ─────────────────────────────────────────────────────────────────────────────

@implementation CADFontSupport

static NSString *_cachedFontsDirectoryPath = nil;

+ (NSString *)fontsDirectoryPath
{
    return _cachedFontsDirectoryPath;
}

+ (void)setupIfNeeded
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSString *path = [self prepareFontsDirectory];
        _cachedFontsDirectoryPath = [path copy];

        if (path.length == 0) {
            NSLog(@"[CADFontSupport] ❌ Failed to prepare fonts directory.");
            return;
        }

        [self installEnvironmentVariables:path];
        [self writeFontMapAtPath:path];

        // List every file in the cache so we can see what ODA will find.
        NSArray<NSString *> *cached = [NSFileManager.defaultManager
            contentsOfDirectoryAtPath:path error:nil];
        NSLog(@"[CADFontSupport] Font search path: %@", path);
        NSLog(@"[CADFontSupport] Files in cache dir: %@",
              cached.count ? [cached componentsJoinedByString:@", "] : @"(empty)");
    });
}

#pragma mark - Internals

+ (NSString *)prepareFontsDirectory
{
    NSFileManager *fm = NSFileManager.defaultManager;

    NSArray<NSString *> *caches = NSSearchPathForDirectoriesInDomains(
        NSCachesDirectory, NSUserDomainMask, YES);
    if (caches.count == 0) return nil;

    NSString *dst = [caches.firstObject
        stringByAppendingPathComponent:kCADFontsCacheSubdirectory];

    NSError *err = nil;
    if (![fm fileExistsAtPath:dst]) {
        if (![fm createDirectoryAtPath:dst
           withIntermediateDirectories:YES attributes:nil error:&err]) {
            NSLog(@"[CADFontSupport] createDirectory failed: %@", err);
            return nil;
        }
    }

    // Locate the bundle's Fonts/ folder reference.
    NSString *bundleFonts = [NSBundle.mainBundle.resourcePath
        stringByAppendingPathComponent:kCADFontsBundleSubdirectory];

    BOOL isDir = NO;
    if ([fm fileExistsAtPath:bundleFonts isDirectory:&isDir] && isDir) {
        NSArray<NSString *> *entries = [fm contentsOfDirectoryAtPath:bundleFonts error:nil];
        NSLog(@"[CADFontSupport] Bundle Fonts/ contents: %@",
              entries.count ? [entries componentsJoinedByString:@", "] : @"(empty)");

        for (NSString *name in entries) {
            if ([name hasPrefix:@"."]) continue;

            NSString *srcPath = [bundleFonts stringByAppendingPathComponent:name];
            NSString *dstPath = [dst stringByAppendingPathComponent:name];

            // README is informational only — skip it.
            if ([name.lowercaseString hasSuffix:@".md"]) continue;

            // Always overwrite FONTMAP.txt so code changes propagate.
            BOOL isFontMap = [name.lowercaseString
                isEqualToString:kCADFontMapFileName.lowercaseString];
            if ([fm fileExistsAtPath:dstPath]) {
                if (!isFontMap) {
                    NSLog(@"[CADFontSupport] Already cached: %@", name);
                    continue;
                }
                [fm removeItemAtPath:dstPath error:nil];
            }

            NSError *copyErr = nil;
            if ([fm copyItemAtPath:srcPath toPath:dstPath error:&copyErr]) {
                NSLog(@"[CADFontSupport] Copied to cache: %@", name);
            } else {
                NSLog(@"[CADFontSupport] Copy FAILED %@ → %@: %@",
                      srcPath, dstPath, copyErr);
            }
        }
    } else {
        NSLog(@"[CADFontSupport] ⚠️ Bundle Fonts/ directory not found at: %@", bundleFonts);
        NSLog(@"[CADFontSupport] ⚠️ Make sure Fonts is added as a folder reference (blue) in Copy Bundle Resources.");
    }

    return dst;
}

+ (void)writeFontMapAtPath:(NSString *)directory
{
    NSString *mapPath = [directory
        stringByAppendingPathComponent:kCADFontMapFileName];

    // Check whether the bundle ships a hand-crafted FONTMAP.txt.
    // If so, the copy step above already placed it in the cache — use it.
    NSString *bundleMap = [[NSBundle.mainBundle.resourcePath
        stringByAppendingPathComponent:kCADFontsBundleSubdirectory]
        stringByAppendingPathComponent:kCADFontMapFileName];

    if (![NSFileManager.defaultManager fileExistsAtPath:bundleMap]) {
        // No bundle-supplied map: write the generated default every launch
        // so tweaking the in-code table is all that's needed.
        NSError *writeErr = nil;
        if (![CADDefaultFontMap() writeToFile:mapPath
                                   atomically:YES
                                     encoding:NSUTF8StringEncoding
                                        error:&writeErr]) {
            NSLog(@"[CADFontSupport] write FONTMAP.txt failed: %@", writeErr);
            return;
        }
        NSLog(@"[CADFontSupport] FONTMAP.txt written.");
    }

    // FONTMAP env var: some ODA host services read it via getenv("FONTMAP").
    setenv("FONTMAP", mapPath.fileSystemRepresentation, 1);
}

+ (void)installEnvironmentVariables:(NSString *)directory
{
    const char *cPath = directory.fileSystemRepresentation;
    if (!cPath) return;

    // ODA's OdDbHostAppServices::findFile() searches:
    //   • ACAD     — general support-file search path (semicolon-separated)
    //   • ACADFONTS— dedicated font search path (checked first for font files)
    setenv("ACAD",           cPath, 1);
    setenv("ACADFONTS",      cPath, 1);
    setenv("ODA_DRAWINGS_PATH", cPath, 1);

    NSLog(@"[CADFontSupport] ACAD=%s", cPath);
}

@end
